name: Publish Docker image

on:
  push:
    tags:
      - '*'

jobs:
  publish-docker:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '14'
        architecture: x64
    - name: Build with Maven (no tests)
      run: ./mvnw clean package -DskipTests

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: worldtiki
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker images on new git tags
      uses: docker/build-push-action@v2
      with:
        tags: worldtiki/pitchfork:latest
        push: true
